### ISSUE TITLE
Clarify file Structure

### ISSUE THREAD

**Issue by TgkCapture** [Mwakanemela/web_development#1]
I want you to clarify on the project structure, am not sure if blog and youtube clone are in one project or if they are two seperate projects.

**Comment by Mwakanemela** [comment]
Oh yeah.....blog is another project in another directory so is youtube clone. and l made a branch special for youtube clone and for more info YouTube clone is just for the interface not interaction

**Comment by TgkCapture** [comment]
Oh Alright, i get
